[phases.setup]
nixPkgs = ['...', 'chromium']

[phases.build]
cmds = ['npm ci', 'npm run build']

[start]
cmd = 'npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/nix/store/chromium/bin/chromium'